CREATE DATABASE adventureworks_db;
USE DATABASE adventureworks_db;

CREATE SCHEMA raw;
USE SCHEMA raw;

CREATE OR REPLACE FILE FORMAT csv_format
TYPE = CSV
FIELD_DELIMITER = '\t'
SKIP_HEADER = 1
FIELD_OPTIONALLY_ENCLOSED_BY = '"'
TRIM_SPACE = TRUE;